
import JobCard from "./JobsCards"; 
const jobs = [
  {
    jobType: "In Office job",
    title: "Senior Analyst - Risk Management | Chennai",
    link: "https://www.jobringer.com/job/senior-analyst-risk-management---chennai/3s0g62o7",
    company: "HINDCO Consulting Services",
    experience: "1 - 6 Years",
    location: "Chennai / India",
    time: "Full Time",
    isVerified: true,
    jobId: "12689",
  },
  {
    jobType: "In Office job",
    title: "Hiring For CA Fresher | Leading CA Firm In Automobile | Kolkata",
    link: "https://www.jobringer.com/job/hiring-for-ca-fresher---leading-ca-firm-in-automobile---kolkata/4p7jtxvl",
    company: "HINDCO Consulting Services",
    experience: " 0 - 2 Years",
    location: " Kolkata / India",
    time: "Full Time",
    isVerified: true,
    jobId: "3076",
  },
  {
    jobType: "In Office job",
    title: "Financial Analyst | Leading Financial Services Co. | Mumbai ",
    link: "https://www.jobringer.com/job/financial-analyst---leading-financial-services-co---mumbai/5nyo2wtv",
    company: "HINDCO Consulting Services",
    experience: "3 - 8 Years",
    location: " Mumbai | Navi Mumbai / Panvel / India",
    time: "Full Time",
    isVerified: true,
    jobId: "1040",
  },
  {
    jobType: "In Office job",
    title: "Recruitment Coordinator - Client Coordination | Gujarat ",
    link: "https://www.jobringer.com/job/recruitment-coordinator-client-coordination---gujarat/lfo8iade",
    company: "HINDCO Consulting Services",
    experience: " 1 - 5 Years",
    location: "Ahmedabad | Mumbai | Surat | Vadodara / Baroda / India",
    time: "Full Time",
    isVerified: true,
    jobId: "3485",
  },
  {
    jobType: "In Office job",
    title: "Office Assistant | Leading FMCG Co. | Kolkata ",
    link: "https://www.jobringer.com/job/office-assistant---leading-fmcg-co---kolkata/6z7fb9j8",
    company: "HINDCO Consulting Services",
    experience: "0 - 2 Years",
    location: "Kolkata / India",
    time: "Full Time",
    isVerified: true,
    jobId: "19803",
  },
  {
    jobType: "In Office job",
    title: "3rd Line Network Security Engineer ",
    link: "https://www.jobringer.com/job/3rd-line-network-security-engineer/f2ahc0w7",
    company: "iConsultera",
    experience: "2 - 5 Years",
    location: " Ahmedabad / India",
    time: " Full Time - Permanent",
    isVerified: true,
    jobId: "33530",
  },
  {
    jobType: "In Office job",
    title: "Pharmacist | Leading Healthcare Co. | Delhi ",
    link: "https://www.jobringer.com/job/pharmacist---leading-healthcare-co---delhi/9qg235sc",
    company: " HINDCO Consulting Services ",
    experience: " 0 - 4 Years",
    location: "Delhi NCR | Gurgaon / Gurugram | Noida / India",
    time: " Full Time - Permanent",
    isVerified: true,
    jobId: "16993",
  },
  {
    jobType: "In Office job",
    title: "Lab Technician | Leading Medical Service | Maharashtra ",
    link: "https://www.jobringer.com/job/lab-technician---leading-medical-service---maharashtra/q5x6c3jk",
    company: " HINDCO Consulting Services ",
    experience: " 0 - 5 Years",
    location: "Mumbai | Nashik | Pune / India",
    time: "Full Time",
    isVerified: true,
    jobId: "3643",
  },
  {
    jobType: "In Office job",
    title: "Revenue Accountant Trainee | Chennai ",
    link: "https://www.jobringer.com/job/revenue-accountant-trainee---chennai/zpa1q5j7",
    company: " HINDCO Consulting Services ",
    experience: " 0 - 1 Years",
    location: "Chennai / India",
    time: "Full Time",
    isVerified: true,
    jobId: "19813",
  },
  {
    jobType: "In Office job",
    title: "Business Development Manager - International Sales | UK ",
    link: "https://www.jobringer.com/job/business-development-manager-international-sales---uk/srqflit0",
    company: " HINDCO Consulting Services ",
    experience: " 8 - 13 Years",
    location: " Indore | Agra | Lucknow | Noida / India",
    time: "Full Time - Internship",
    isVerified: true,
    jobId: "3557",
  },
  {
    jobType: "In Office job",
    title: "Exhibition Tour Guide ",
    link: "https://www.jobringer.com/job/exhibition-tour-guide/vial4or5",
    company: " HINDCO Consulting Services ",
    experience: "0 - 5 Years",
    location: "Delhi NCR | Hyderabad - Secunderabad | Mumbai / India",
    time: "Full Time",
    isVerified: true,
    jobId: "1284",
  },
  {
    jobType: "In Office job",
    title: "Area Sales Manager | Leading NBFC | Ahmedabad ",
    link: "https://www.jobringer.com/job/area-sales-manager---leading-nbfc---ahmedabad/0hz52mok",
    company: " HINDCO Consulting Services ",
    experience: "5 - 10 Years",
    location: "Ahmedabad / India",
    time: "Full Time",
    isVerified: true,
    jobId: "3930",
  },
  {
    jobType: "In Office job",
    title: "Warehouse Manager FG | Leading Pharma Company | Indore ",
    link: "https://www.jobringer.com/job/warehouse-manager-fg---leading-pharma-company---indore/zh70p9n8",
    company: " HINDCO Consulting Services ",
    experience: "7 - 12 Years",
    location: "Indore | Pithampur / India",
    time: "Full Time",
    isVerified: true,
    jobId: "405",
  },
  {
    jobType: "In Office job",
    title: "Officer - Material Planning | Hyderabad ",
    link: "https://www.jobringer.com/job/officer-material-planning---hyderabad/koptsryh",
    company: " HINDCO Consulting Services ",
    experience: "3 - 8 Years",
    location: " Hyderabad - Secunderabad / India",
    time: "Full Time",
    isVerified: true,
    jobId: "13006",
  },
  {
    jobType: "In Office job",
    title: "Executive QC | A Leading Pharmaceutical Company | Pithampur",
    link: "https://www.jobringer.com/job/executive-qc---a-leading-pharmaceutical-company---pithampur/pfhc40ai",
    company: " HINDCO Consulting Services ",
    experience: "3 - 8 Years",
    location: "Ahmedabad | Bhopal | Daman | Indore / India",
    time: "Full Time",
    isVerified: true,
    jobId: "363",
  },
];

const JobList = () => {
  return (
    <>
      {jobs.map((job, index) => (
        <JobCard key={index} {...job} index={index}/>
      ))}
      </>
  );
};

export default JobList;
